=== waysys/SuiteDreams/suite_dreams_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 rel. 3 (x64) (http://www.altova.com) by William A Shaffer (Waysys LLC) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="TestSuite" type="TypeTestSuite">
		<xs:annotation>
			<xs:documentation>This element is the root of the test suite specification.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="TypeTestSuite">
		<xs:annotation>
			<xs:documentation>
	This type defines the top level structure of test suite specification.
	</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="SuiteName" type="xs:string"/>
			<xs:element name="SuiteId" type="xs:string"/>
			<xs:element name="Author" type="xs:string"/>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="ProjectName" type="xs:string"/>
			<xs:element name="Version" type="xs:string"/>
			<xs:element name="Fixture" type="xs:string">
				<xs:annotation>
					<xs:documentation>
			This is the full class name of the Gosu class that is the fixture for this test case.
			</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Count">
				<xs:annotation>
					<xs:documentation>
			Count is the number of test cases that will be generated.  
			</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Seed">
				<xs:annotation>
					<xs:documentation>
				This element specifies the seed for the random number generator.  By setting different seeeds in different test cases, different sequences of randome number are generated in different tests.
				</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Product" type="TypeProduct">
				<xs:annotation>
					<xs:documentation>
			The product element contains the definition of the product.
			</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Policy" type="TypePolicy">
				<xs:annotation>
					<xs:documentation>
			The policy element contains properties to be set on the policy.
			</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TypeProduct">
		<xs:annotation>
			<xs:documentation>The product element describes the product being tested.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ProductCode" type="xs:string"/>
			<xs:element name="QuestionSet" type="TypeQuestionSet" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Coverable" type="TypeCoverable" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TypePolicy">
		<xs:annotation>
			<xs:documentation>The policy element provides the information for defining the policy</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Property" type="TypeProperty" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="Quote" type="TypeEmpty" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Bind" type="TypeEmpty" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TypeEmpty">
		<xs:annotation>
			<xs:documentation>
	This type supports empty tags for Quote and Bind.
	</xs:documentation>
		</xs:annotation>
	</xs:complexType>
	<xs:complexType name="TypeQuestionSet">
		<xs:annotation>
			<xs:documentation>The question element defines a question set</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="QuestionSetCode" type="xs:string"/>
			<xs:element name="Question" type="TypeQuestion" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TypeQuestion">
		<xs:annotation>
			<xs:documentation>The question element identifies a question and a set of valid answers</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="QuestionCode" type="xs:string"/>
			<xs:element name="Answer" type="TypeValue" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TypeValue">
		<xs:annotation>
			<xs:documentation>
	The value type element stores a value of a property.  A property can have multiple values, each with a
	weight to determine which one is chosen for the test case.
	</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="weight" use="optional" default="100"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="TypeProperty">
		<xs:annotation>
			<xs:documentation>
		The Property element represents the action of setting the value of a property on a fixture or entity.
		</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="PropertyName" type="xs:string"/>
			<xs:element name="Value" type="TypeValue" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute ref="weight" use="optional" default="100"/>
		<xs:attribute name="class" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="unique"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="TypeCoverable">
		<xs:annotation>
			<xs:documentation>
		A coverable is an entity that has properties and coverages.
		</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="CoverableName" type="xs:string"/>
			<xs:element name="Property" type="TypeProperty" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Coverage" type="TypeCoverage" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute ref="weight" use="optional" default="100"/>
		<xs:attribute name="selection">
			<xs:annotation>
				<xs:documentation>
		Attribute selection specifies whether the coverable is selected or created.  Coverables being
		selected exist on the policy by default.  Coverables that are being created are optional and are
		not present on the policy by default.
		</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="create"/>
					<xs:enumeration value="select"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="minCount">
			<xs:annotation>
				<xs:documentation>
		Attribute minCount specifies the minimum number of this coverable to be created.  The attribute
		is meaningful only if the coverable is being created.  If count is the number of coverables,
		count is a random number such that count is between minCount and maxCount.
		</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="0"/>
					<xs:maxInclusive value="1000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="maxCount">
			<xs:annotation>
				<xs:documentation>
		Attribute maxCount specifies the maximum number of this coverable to be created.  The attribute
		is meaningful only if the coverable is being created.  
		MinCount must be less than or equal to maxCount.
		</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="0"/>
					<xs:maxInclusive value="1000"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="TypeCoverage">
		<xs:annotation>
			<xs:documentation>
	A coverage is the amount of risk or protection provided by the insurer for an entity.
	</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="CoverageCode" type="xs:string"/>
			<xs:element name="CoverageTerm" type="TypeCoverageTerm" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute ref="weight"/>
	</xs:complexType>
	<xs:complexType name="TypeCoverageTerm">
		<xs:annotation>
			<xs:documentation>
	A coverage term is a limit or deductible or other attribute of a coverage.
	</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="CoverageTermCode"/>
			<xs:element name="Term" type="TypeValue" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:attribute name="weight">
		<xs:simpleType>
			<xs:annotation>
				<xs:documentation>
		The weight attribute controls the probility of a feature being selected 
		for inclusion in the test case.  
		The weight is an integer between 0 and 100 inclusive.  
		If the weight is 0, the feature is guaranteed 
		to not be included.  If the weight is 100, the feature is guaranteed to be included.  For integers
		in between, a random selector between 1 and 100 is generated, if the selector is less than or 
		equal to the weight, the feature is selected.
	</xs:documentation>
			</xs:annotation>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="1000"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
</xs:schema>

=== waysys/SuiteDreams/HOSubmissionHO5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 rel. 3 (x64) (http://www.altova.com) by William A Shaffer (Waysys LLC) -->
<!--Sample XML file generated by XMLSpy v2017 rel. 3 (x64) (http://www.altova.com)-->
<TestSuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="suite_dreams_schema.xsd">
	<SuiteName>HomeownersSubmission</SuiteName>
	<SuiteId>HO01</SuiteId>
	<Author>Bill Shaffer</Author>
	<Description>These test cases produce homeowners submissions that are quoted and bound.</Description>
	<ProjectName>FMIGIS</ProjectName>
	<Version>24-Aug-2018</Version>
	<Fixture>fmi.gfit.policycenter.policycenter.HomeownersSubmissionFixtureFMI</Fixture>
	<Count>10</Count>
	<Seed>067887</Seed>
	<Product>
		<ProductCode>Homeowners</ProductCode>
		<QuestionSet>
			<QuestionSetCode>HOGAGenericPreQual_HOE</QuestionSetCode>
			<Question>
				<QuestionCode>HOHousehold_HOE_FMI</QuestionCode>
				<Answer>no</Answer>
			</Question>
			<Question>
				<QuestionCode>HOHomeLessThanSixFeet_HOE_FMI</QuestionCode>
				<Answer>no</Answer>
			</Question>
			<Question>
				<QuestionCode>HOSwimmingPool_HOE_FMI</QuestionCode>
				<Answer>no</Answer>
			</Question>
			<Question>
				<QuestionCode>HOTrampolineOnPremises_HOE_FMI</QuestionCode>
				<Answer>no</Answer>
			</Question>
		</QuestionSet>
		<Coverable>
			<CoverableName>policy line</CoverableName>
			<Coverage weight="100">
				<CoverageCode>HOLI_Personal_Liability_HOE</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HOLI_Liability_Limit_HOE</CoverageTermCode>
					<Term weight="34">1000000</Term>
					<Term weight="34">300000</Term>
					<Term weight="34">500000</Term>
				</CoverageTerm>
			</Coverage>			
			<Coverage weight="100">
				<CoverageCode>HOLI_Med_Pay_HOE</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HOLI_MedPay_Limit_HOE</CoverageTermCode>
					<Term weight="34">10000</Term>
					<Term weight="34">3000</Term>
					<Term weight="34">5000</Term>
				</CoverageTerm>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HOLI_IdentityTheftPersonalInjury_MPL55_FMI</CoverageCode>
			</Coverage>			
			<Coverage weight="20">
				<CoverageCode>HOLI_AdditionalInsuredPremises_MPL26_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HOLI_FarmersSpecialLiability_MPL30_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HOLI_AnimalCollision_MPL35_FMI</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HOLI_NumberofAnimals_MPL35_FMI</CoverageTermCode>
					<Term weight="50">1</Term>
					<Term weight="50">10</Term>
				</CoverageTerm>
			</Coverage>
			<Coverage weight="0">
				<CoverageCode>HOLI_UnitOwnersPropertySupplement_MPL77_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HOLI_FuelOilLimitations_FM227_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HOLI_FarmTypeStructures_MPL33_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="0">
				<CoverageCode>HOLI_IncidentalBusiness_MPL52_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HOLI_ValuableArticles_MPL17_FMI</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HOLI_ValuableArticles_MPL17_Limit_FMI</CoverageTermCode>
					<Term weight="12">15000</Term>
					<Term weight="12">3000</Term>
					<Term weight="12">5000</Term>
					<Term weight="12">1000</Term>
					<Term weight="12">10000</Term>
					<Term weight="12">20000</Term>
					<Term weight="12">2000</Term>
					<Term weight="12">4000</Term>
					<Term weight="12">25000</Term>
				</CoverageTerm>
			</Coverage>

			<Coverage weight="0">
				<CoverageCode>HOLI_SpecialBusiness_MPL58_FMI</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HOLI_SpecialBusiness_MPL58_Limit_FMI</CoverageTermCode>
					<Term>100000</Term>
				</CoverageTerm>
			</Coverage>
			<Coverage weight="0">
				<CoverageCode>HOLI_MedicalPaymentsTenants_MDL62_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HOLI_RelatedStructures_MPL32_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HOLI_WatercraftLiability_MPL20_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HOLI_Liability34FamilyDwelling_MHO31_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="0">
				<CoverageCode>HOLI_Umbrella_MPL80_FMI</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HOLI_Umbrella_Cov_Limit_FMI</CoverageTermCode>
					<Term weight="20">3000000</Term>
					<Term weight="20">2000000</Term>
					<Term weight="20">1000000</Term>
					<Term weight="20">4000000</Term>
					<Term weight="20">5000000</Term>
				</CoverageTerm>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HOLI_OutboardMotorsMotorboats_MPL19_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HOLI_TheftDeductible_MPL37_FMI</CoverageCode>
			</Coverage>
		</Coverable>
		<Coverable>
			<CoverableName>dwelling</CoverableName>
			<Property>
				<PropertyName>DistanceToFireHydrant</PropertyName>
				<Value>10</Value>
			</Property>
			<Property>
				<PropertyName>ResidenceType</PropertyName>
				<Value>Fam1</Value>
			</Property>
			<Property>
				<PropertyName>DwellingUsage</PropertyName>
				<Value>prim</Value>
			</Property>
			<Property>
				<PropertyName>Occupancy</PropertyName>
				<Value>owner</Value>
			</Property>
			<Property>
				<PropertyName>UnitsNumber</PropertyName>
				<Value>One</Value>
			</Property>
			<Coverage weight="100">
				<CoverageCode>HODW_SectionI_Ded_HOE</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HODW_SectionI_Ded_3_5_FMI</CoverageTermCode>
					<Term weight="10">2000</Term>
					<Term weight="10">300</Term>
					<Term weight="10">200</Term>
					<Term weight="10">500</Term>
					<Term weight="10">1000</Term>
					<Term weight="10">10000</Term>
					<Term weight="10">400</Term>
					<Term weight="10">750</Term>
					<Term weight="10">5000</Term>
					<Term weight="10">3000</Term>
					<Term weight="10">7500</Term>
				</CoverageTerm>
			</Coverage>			
			<Coverage weight="100">
				<CoverageCode>HODW_Dwelling_Cov_HOE</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HODW_Dwelling_Cov_Limit_FMI</CoverageTermCode>
					<Term weight="100">200000</Term>
				</CoverageTerm>
				<CoverageTerm>
					<CoverageTermCode>HODW_DwellingValuation_HOE</CoverageTermCode>
					<Term weight="50">Replacement</Term>
					<Term weight="50">Actual</Term>
				</CoverageTerm>
			</Coverage>		
			<Coverage weight="100">
				<CoverageCode>HODW_Related_Structure_FMI</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HODW_Related_Structures_Limit_Increased_FMI</CoverageTermCode>
					<Term>0</Term>
				</CoverageTerm>
				<CoverageTerm>
					<CoverageTermCode>HODW_Related_Structures_Limit_FMI</CoverageTermCode>
					<Term>20000</Term>
				</CoverageTerm>
			</Coverage>				
			<Coverage weight="100">
				<CoverageCode>HODW_Personal_Property_HOE</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HODW_PersonalPropertyLimit_Increased_FMI</CoverageTermCode>
					<Term>0</Term>
				</CoverageTerm>
				<CoverageTerm>
					<CoverageTermCode>HODW_Personal_Property_Limit_FMI</CoverageTermCode>
					<Term>140000</Term>
				</CoverageTerm>
			</Coverage>			
			<Coverage weight="100">
				<CoverageCode>HODW_Loss_Of_Use_HOE</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HODW_Loss_Of_Use_Limit_Increased_FMI</CoverageTermCode>
					<Term>0</Term>
				</CoverageTerm>
				<CoverageTerm>
					<CoverageTermCode>HODW_Loss_Of_Use_Limit_FMI</CoverageTermCode>
					<Term>60000</Term>
				</CoverageTerm>
			</Coverage>			
			<Coverage weight="100">
				<CoverageCode>HODW_ComputerCoverage_MHO14_FMI</CoverageCode>
			</Coverage>	
			<Coverage weight="100">
				<CoverageCode>HODW_IncreasedCost_MHO48_FMI</CoverageCode>
			</Coverage>					
			<Coverage weight="20">
				<CoverageCode>HODW_Association_MPL65_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HODW_Other_MPL65_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HODW_Townhouse_MPL67_68_69_FMI</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HODW_NumberofUnits_MPL67_FMI</CoverageTermCode>
					<Term weight="34">5</Term>
					<Term weight="34">9</Term>
					<Term weight="34">1</Term>
				</CoverageTerm>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HODW_LossPropTransCoinsStamps_MPL93_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HODW_SumpPump_FM152_FMI</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HODW_SumpPump_FM152_Limit_FMI</CoverageTermCode>
					<Term weight="13">10000</Term>
					<Term weight="13">20000</Term>
					<Term weight="13">5000</Term>
					<Term weight="13">7500</Term>
					<Term weight="13">25000</Term>
					<Term weight="13">50000</Term>
					<Term weight="13">15000</Term>
					<Term weight="13">3000</Term>
				</CoverageTerm>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HODW_ServiceLine_FM158_FMI</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HODW_ServiceLine_FM158_Limit_FMI</CoverageTermCode>
					<Term weight="34">25000</Term>
					<Term weight="34">10000</Term>
					<Term weight="34">15000</Term>
				</CoverageTerm>
			</Coverage>
			<Coverage weight="0">
				<CoverageCode>HODW_Combination_Dwelling_FMI</CoverageCode>
				<CoverageTerm>
					<CoverageTermCode>HODW_Combination_Dwelling_Limit_FMI</CoverageTermCode>
					<Term>200000</Term>
				</CoverageTerm>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HODW_EquipmentBreakdown_FM157_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HODW_ExtendedReplacementCost_MHO12_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
				<CoverageCode>HODW_CovCExtendedLoss_MPL18_FMI</CoverageCode>
			</Coverage>
			<Coverage weight="20">
